package project_coursemanagement.ptit_cntt1_it211_project_coursemanagement.service;

import project_coursemanagement.ptit_cntt1_it211_project_coursemanagement.model.dto.request.RegisterStudentDTO;
import project_coursemanagement.ptit_cntt1_it211_project_coursemanagement.model.dto.response.RegisterUserResponse;

public interface PublicService {
    RegisterUserResponse createNewStudentAccounts(RegisterStudentDTO registerStudentDTO);
}
